### ISSUE TITLE
Anchor links for headings

### ISSUE THREAD

**Issue by nuuttitoivola** [Seravo/docs#31]
The headings on the seravo.com/docs should have an easy to use anchor link, preferably something the users can click to save the link on the clipboard.

We already have the basic functionality present, as in: https://seravo.com/docs/configuration/nginx/#how-to-create-your-own-rules

**Comment by ottok** [comment]
I like how the Github Markdown parser makes all anchors clickable links as hower on icons. See yourself at  https://github.com/Seravo/docs
![Screenshot from 2019-06-20 15-04-07](https://user-images.githubusercontent.com/668724/59851410-dcb34d00-936c-11e9-9188-ddb490234908.png)

Maybe Mikko, Markus or Samuli could take a shot at this?

**Comment by elguitar** [comment]
I did some quick investigation.

Anchors could be achieved by using different syntax for headers ([source](https://gist.github.com/asabaylus/3071099)), but that would break workflow, so it doesn't solve this problem.

[Someone on stackoverflow](https://stackoverflow.com/a/53893197) suggests that this can be achieved by a self-made plugin. It's five lines of ruby which converts headers into more complex entities. However, [github-pages doesn't allow custom plugins](https://stackoverflow.com/a/40474421), which makes it easier to use javascript. 

Couple of plausible javascript implementations are [AnchorJS](https://milanaryal.com.np/adding-hover-anchor-links-to-header-on-github-pages-using-jekyll/) and [plain CSS + JS](https://ben.balter.com/2014/03/13/pages-anchor-links/)

There's also [this JS free implementation](https://github.com/allejo/jekyll-anchor-headings), which seems like quite a magic to me.

**Comment by elguitar** [comment]
3c2554721f44794b4b963a3020f2d6724af3b66f seems to not work in production :disappointed:
