### ISSUE TITLE
Update Vagrant installation instructions

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/docs#39]
Instructions in https://seravo.com/docs/development/how-to-install/ don't seem to be very up do date. Vagrant >= 2.2.7 supports VirtualBox 6.1 and I saw no performance issues using it.

Some things to note:
- Latest Vagrant and VirtualBox work together
- Latest Vagrant not available even in Ubuntu 20.04 LTS so instructions maybe needed 
- Old versions of https://github.com/Seravo/wordpress `Vagrantfile` don't work at all with the latest Vagrant

Was there reasons to recommend VirtualBox 5.2 other than incompatibility of 6.1 and slowness of 6.0? Should we start recommending VirtualBox 6.1?

**Comment by elguitar** [comment]
Closing via https://github.com/Seravo/docs/commit/df283705fec9f5b4511869045491af867f4466c8
