### ISSUE TITLE
Update instructions on resetting a shadow using a graphical option

### ISSUE THREAD

**Issue by pekkakortelainen** [Seravo/docs#40]
Instructions on how to reset a shadow via wp-admin suggest Tools -> Shadows. This path seems to be deprecated as shadows are found under Site Status in wp-admin and there is no option Shadows under Tools menu.

https://seravo.com/docs/deployment/shadows/#graphical-option-via-wp-admin

**Comment by ottok** [comment]
Do you want to make a PR about this fix yourself? I am sure e.g. @elguitar or @JoosuaKoskinen can help you out with git basics.

**Comment by pekkakortelainen** [comment]
Sure thing @ottok.

**Comment by pekkakortelainen** [comment]
Fixed in https://github.com/Seravo/docs/commit/95be72baf1285b4ae31007f75421f7a0084a155b.

**Comment by elguitar** [comment]
@pekkakortelainen I will close this for you :wink: Issues that have been fixed, should be closed.
