### ISSUE TITLE
Evaluate current use of Ruby/Jekyll

### ISSUE THREAD

**Issue by ottok** [Seravo/docs#44]
Our current seravo.com/docs has served us well, but it might need a structural upgrade.

Biggest annoyances at the moment:
- Pages are not easy to render locally, the experience is much more archaic than e.g. compared to [sites that use Hugo](https://gitlab.com/apparmor/apparmor.net/-/blob/master/README.md)
- Instead of every article being a _post_ with a date, they should be dateless pages so the "information architecture" would be correct.
- Our man pages are not part of the docs and there is no easy way to append them there.

I have been looking at how nice the [Pydantic docs](https://pydantic-docs.helpmanual.io/) look like, and they have a built-in search (just like we need) with some additional features, and is build using Python and all build code and Github Actions are [available](https://github.com/samuelcolvin/pydantic/blob/master/.github/workflows/docs-preview.yml) publicly.

**Comment by sjaks** [comment]
Articles are now pages and man pages have been hosted under seravo.com/docs for a while.
I will take a look into the first point while updating the documentation: https://github.com/Seravo/docs/issues/69
