### ISSUE TITLE
Man pages have some incorrect formatting

### ISSUE THREAD

**Issue by pekkakortelainen** [Seravo/docs#55]
With man pages the double dashes in front of command flags are being converted to an _en dash_, a single character. This can cause confusion if a user is copying flags or example commands straight to their terminal.

Under `wp-test-whitelist` [man page](https://seravo.com/docs/man/wp-test-whitelist/) we have two examples. They are formatted like this when copied:

`wp-test-whitelist –add “https://example.com/favicon.ico 404 (Not Found)”`

`wp-test-whitelist –add “.*example\.com/mylibrary\.js.*404.*” –regex`

The add and regex flags don't have double dashes in front of them but instead the en dash. This seems to be happening on any man page with any occurrences of double dashes.

**Comment by ottok** [comment]
True, this makes copy-pasting commands inconvenient. Maybe @sjaks could take a view?

**Comment by pekkakortelainen** [comment]
Another observation - also the quotation marks are converted to left and right double quotation marks, respectively.
