### ISSUE TITLE
Update PHP docs

### ISSUE THREAD

**Issue by ottok** [Seravo/docs#57]
The page https://seravo.com/docs/configuration/php7-hhvm/ has "PHP 7" in the title. Now with PHP 8, the title should be just "PHP version" or something. Also it would be better if the URL was https://seravo.com/docs/configuration/php-versions/ (and with the old URL redirecting to the new one to avoid link rot).

Naturally the page itself also needs to be updated to include PHP 8 and drop PHP 7(.0). While 7.2 and 7.3 continue to be available, the page should clearly state that PHP 7.4 is currently the recommended version everybody should be using.

A link to https://www.php.net/supported-versions.php would also nicely complement it.

**Comment by elguitar** [comment]
Closed via https://github.com/Seravo/docs/commit/325c31dec665de96955f91285c9dc61db80deb51
