### ISSUE TITLE
Start using branch 'master' instead of 'gh-pages' and deploy using GitHub Actions

### ISSUE THREAD

**Issue by ottok** [Seravo/docs#60]
Due to historical reasons GitHub pages required that the contents was on a branch named *gh-pages*. I suspect this is not required anymore, not at least if GitHub pages deployment is done using GitHub Actions.

TODO:
- [ ] Rename branch `gh-pages` to `master` to follow the convention of regular git repos
- [ ] Activate GitHub Actions to deploy from `master` to seravo.com/docs: https://github.com/Seravo/docs/actions/new
    ![image](https://user-images.githubusercontent.com/668724/104930616-0cde2a00-59ae-11eb-9681-98c49186836a.png)

**Comment by ypcs** [comment]
No need to use actions, branch is nowadays selectable directly from repo settings: https://github.com/Seravo/docs/settings

![Screenshot from 2021-01-19 07-35-10](https://user-images.githubusercontent.com/97568/104992108-fc1eca00-5a28-11eb-9be0-1d6810c5710d.png)

**Comment by ottok** [comment]
Thanks for noticing. GitHub Pages branch changed and repo default branch renamed from `gh-pages` to `master` in repo settings.
